services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    env_file: ".env"
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_USERNAME=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    network_mode: "host"

  server-php:
    build:
      context: .
    container_name: server-php
    x-develop:
      watch:
        - action: sync
          path: ./${PHP_PATH_LOCAL}
          target: /${PHP_PATH_DOCKER}
    env_file: ".env"
    volumes:
      - ./${PHP_PATH_LOCAL}:/${PHP_PATH_DOCKER}
    working_dir: /${PHP_PATH_DOCKER}
    command: php artisan serve
    ports:
      - ${PHP_PORT}:${PHP_PORT}
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
