services:
  server-bd:
    image: bitnami/postgresql:latest
    container_name: server-bd
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=laravel
      - SERVICE_NAME=localhost
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    network_mode: "host"

  server-php:
    build:
      context: .
    container_name: server-php
    volumes:
      - ./server-php:/usr/src/phpapp
    working_dir: /usr/src/phpapp
    command: php artisan serve
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - server-bd
